const mongoose = require('mongoose')

const contactSchema = mongoose.Schema({

    user_id: {
        type: mongoose.Schema.Types.ObjectId,  // as the id is generated by Mongo itself
        ref: 'User',   // tells from which model we are going to get the ID
        required: true
    },

    name: {
        type: String,
        required: [true, "Please enter the contact name"]
    },
    email: {
        type: String,
        required: [true, "Please enter the email"]
    },
    phone: {
        type: String,
        required: [true, "Please enter the phone number"]
    }
}, {
    timestamps: true,
})

module.exports = mongoose.model('Contact', contactSchema);